blank_issues_enabled: true
contact_links:
  - name: ğŸ“ƒ æ–‡æ¡£é—®é¢˜ ï½œ Documentation Issue
    url: https://github.com/openkraken/website/issues/new
    about: æ–‡æ¡£é—®é¢˜è¯·åœ¨è¿™é‡Œåé¦ˆã€‚ ï½œ Please file documentation issues here.

