name: example build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
#       设置 bridge 编译环境
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.22.x'
      - run: npm i
      
      
#       设置 flutter 环境
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter config --enable-macos-desktop 
      - run: flutter doctor -v 
      
      - name: android app build
        run: |
              npm run build:bridge:android:release
              cd kraken/
              flutter pub get
              cd example/
              flutter build apk --release  

      - name: macos app build
        run: |
              npm run build:bridge:macos:release
              cd kraken/
              flutter pub get
              cd example/
              flutter build macos --release

      - name: ios app build              
        run: |
              npm run build:bridge:ios:release  
              cd kraken/
              flutter pub get
              cd example/
              flutter build ios --release --no-codesign
