name: example build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#       设置 bridge 编译环境
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.21.x'
          
      - run: npm i
      # - run: npm run build:bridge:android:release
#       - run: npm run build:bridge:macos:release
#       - run: npm run build:bridge:ios:release  
      
      - run: npm run build:bridge:all:release
      
#       设置 flutter 环境
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter config --enable-macos-desktop 
      - run: flutter config --enable-linux-desktop 
      
      - run: |
              cd kraken/
              flutter pub get
              cd example/
              flutter build apk --release  # 编译不通过

      - name: build macos
        run: |
              cd kraken/
              flutter pub get
              cd example/
              flutter build macos --release
              
      - run: |
              cd kraken/
              flutter pub get
              cd example/
              flutter build ios --release --no-codesign
