name: example build linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#       设置 bridge 编译环境
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: '3.22.x'
          
      - run: npm i
      - run: npm run build:bridge:linux:release

#       设置 flutter 环境
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
      - run: flutter config --enable-linux-desktop 
      - run: |
              sudo apt-get update
              sudo apt-get install ninja-build pkg-config libgtk-3-dev -y
      - run: flutter doctor -v 

      - name: linux app build
        run: |
              cd kraken/
              flutter pub get
              cd example/
              flutter build linux --release

