name: Publish Kraken To pub.dev Nightly

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # Run workflow every day at 21:00
    - cron:  '0 21 * * *'
  workflow_dispatch:

env:
  nodeVersion: "16"
  cmakeVersion: "3.22.x"
  flutterVersion: "2.2.0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux_binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: jwlawson/actions-setup-cmake@v1.11
        with:
          cmake-version: "3.22.x"

      - run: npm i
      - run: npm run build:bridge:linux:release
      - uses: actions/upload-artifact@v2
        with:
          name: linux_binary
          path: bridge/build/linux/

  publishToPubDev:
    needs: build_linux_binary
    runs-on: [self-hosted, flutter_2.2.0]
    steps:
    - uses: actions/checkout@v2
    - name: NPM INSTALL
      run: npm install
    - name: Set up nightly version
      run: node scripts/set_up_nightly_release.js
    - name: Build bridge binary
      run: npm run build:bridge:all:release
    - uses: actions/download-artifact@v2
      with:
        name: linux_binary
        path: bridge/build/linux/
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutterVersion }}
    - name: Publish to dart.dev
      run: cd kraken && flutter pub publish --force
